-- ============================================================================
-- TERANGA PARK VILLAS — Migration Supabase
-- À exécuter une fois dans le SQL Editor du dashboard Supabase.
-- Gère : site_setting, leads, buckets Storage, politiques RLS.
-- Aucun dashboard admin n'est nécessaire : tout se gère depuis Supabase.
-- ============================================================================

-- ────────────────────────────────────────────────────────────────────────────
-- 1. TABLE site_setting
-- Une seule ligne (id = 1) à éditer directement depuis le dashboard Supabase.
-- Laisser une valeur vide → le site utilise sa valeur par défaut propre.
-- ────────────────────────────────────────────────────────────────────────────
create table if not exists public.site_setting (
  id                bigint generated by default as identity primary key,
  hero_image_url    text,
  gallery_image_1   text,
  gallery_image_2   text,
  gallery_image_3   text,
  gallery_image_4   text,
  gallery_image_5   text,
  gallery_image_6   text,
  pdf_url           text,
  whatsapp_number   text,
  price             text,
  availability_text text,
  hero_title        text,
  hero_subtitle     text,
  updated_at        timestamptz not null default now()
);

-- Ligne par défaut (contenu actuel du site — modifiable ensuite via le dashboard)
insert into public.site_setting
  (id, whatsapp_number, price, availability_text, hero_title, hero_subtitle)
values
  (1,
  '+221 77 361 59 44',
   '157 200 000 FCFA',
   'Prix de lancement pour les premières villas disponibles.',
   'Teranga Park Villas',
   'À Nguerigne Peulh, à proximité de Ngaparou — résidence privée, moderne et sécurisée.')
on conflict (id) do nothing;

-- RLS : lecture publique autorisée, écriture interdite depuis le site public.
alter table public.site_setting enable row level security;

drop policy if exists "site_setting_readable_by_anyone" on public.site_setting;
create policy "site_setting_readable_by_anyone"
  on public.site_setting
  for select
  to anon, authenticated
  using (true);

-- Aucune policy INSERT/UPDATE/DELETE pour anon/authenticated :
-- seul le dashboard Supabase (service role) peut modifier les réglages.

-- ────────────────────────────────────────────────────────────────────────────
-- 2. TABLE leads
-- Les visiteurs peuvent uniquement INSÉRER un prospect.
-- Lecture / modification / suppression : dashboard Supabase uniquement.
-- Colonnes optionnelles de qualification (formulaire long existant conservé).
-- ────────────────────────────────────────────────────────────────────────────
create table if not exists public.leads (
  id                  uuid primary key default gen_random_uuid(),
  created_at          timestamptz not null default now(),
  full_name           text not null,
  phone               text not null,
  country             text not null,
  source              text default 'direct',
  utm_source          text,
  utm_medium          text,
  utm_campaign        text,
  requested_document  boolean not null default false,
  -- Champs optionnels remplis par le formulaire de qualification complet
  project_type        text,
  budget              text,
  purchase_timeline   text,
  financing           text,
  visit_preference    text
);

alter table public.leads enable row level security;

drop policy if exists "leads_insert_by_anyone" on public.leads;
create policy "leads_insert_by_anyone"
  on public.leads
  for insert
  to anon, authenticated
  with check (true);

-- Pas de policy SELECT / UPDATE / DELETE : impossible de lire ou altérer
-- les prospects depuis le site public. Consultation via dashboard Supabase.

-- ────────────────────────────────────────────────────────────────────────────
-- 3. BUCKETS STORAGE
-- teranga-images   : photos du site (hero, galerie) — URL publiques
-- teranga-documents: dossier PDF commercial — URL publique (téléchargement)
-- Upload des fichiers depuis le dashboard Supabase → Storage,
-- puis copier l'URL publique dans site_settings.
-- ────────────────────────────────────────────────────────────────────────────
insert into storage.buckets (id, name, public)
values
  ('teranga-images', 'teranga-images', true),
  ('teranga-documents', 'teranga-documents', true)
on conflict (id) do nothing;

-- Lecture publique des deux buckets
drop policy if exists "teranga_public_read_images" on storage.objects;
create policy "teranga_public_read_images"
  on storage.objects
  for select
  to anon, authenticated
  using (bucket_id = 'teranga-images');

drop policy if exists "teranga_public_read_documents" on storage.objects;
create policy "teranga_public_read_documents"
  on storage.objects
  for select
  to anon, authenticated
  using (bucket_id = 'teranga-documents');

-- Écriture réservée aux utilisateurs authentifiés (le dashboard utilise le
-- service role et n'est donc pas concerné). Le public ne peut rien uploader.
drop policy if exists "teranga_auth_write_images" on storage.objects;
create policy "teranga_auth_write_images"
  on storage.objects
  for insert
  to authenticated
  with check (bucket_id = 'teranga-images');

drop policy if exists "teranga_auth_write_documents" on storage.objects;
create policy "teranga_auth_write_documents"
  on storage.objects
  for insert
  to authenticated
  with check (bucket_id = 'teranga-documents');

-- ────────────────────────────────────────────────────────────────────────────
-- 4. INDEX (propreté des consultations futures)
-- ────────────────────────────────────────────────────────────────────────────
create index if not exists leads_created_at_idx on public.leads (created_at desc);
create index if not exists leads_source_idx on public.leads (source);
